#!/usr/bin/env ruby
#
#   The most hated, trivial programming interview task of all!
#   Here's the scoop:
#
#       Print the integers 1 through 100, but:
#           If divisible by 3, print "Fizz"
#           If divisible by 5, print "Buzz"
#           If divisible by 3 and 5, print "FizzBuzz"

(1..100).each do |n|
    if (n % 15 == 0)
        puts "FizzBuzz"
    elsif (n % 3 == 0)
        puts "Fizz"
    elsif (n % 5 == 0)
        puts "Buzz"
    else
        puts n
    end
end
