#!/usr/bin/env zsh
#
#   Add fortunes to your own personal collection and make them a part of the
#   system's fortune collection
#

my_fortune_file="$HOME/documents/write/jdc-fortunes"

cd ~/SpiderOak-Hive/fortunes
# Edit the file
vim $my_fortune_file;

# Convert it to a form fortune expects
strfile $my_fortune_file;

# And copy both to the dir where fortune expects to find it.
echo "Adding '$my_fortune_file' to system fortunes.."
sudo cp -v $my_fortune_file* /usr/share/games/fortunes
