#!/usr/bin/env zsh
#
#   TRY `du -sm * | sort -rn` instead!
#
# See disk usage of everything in the current directory, sorted by size and human readable.
#   -I had to roll my own 'human-readable' here -- it's just MB
#
#   -..And then it seems `du` has a '-m' option, making the solution just a pipe
#   through sort -rn, instead of this hack.  Nothing new under the sun..

du -s * | sort -rn | perl -pe '($s) = /(\d+)/;printf(qq(%3dM\t), int($s / 1024))'
