#!/usr/bin/env ruby
#
#   Try `du -sm * | sort -rn` instead!
#
# See disk usage of everything in the current directory, sorted by size and human readable.
#   -I had to roll my own 'human-readable' here -- it's just MB
#
#du -s * | sort -rn | perl -pe '($s) = /(\d+)/; printf(qq(%3dM\t), int($s / 1024))'

output = `du -sc * | sort -rn`

output.split('\n').each do |line|
  puts line.sub(/(\d+)\s/, "xxx ") 
end
