#!/usr/bin/env zsh
#
#   Show a random fortune using an online API.
#
#   An argument is passed along to the URL. 
#
#   More info at: http://iheartquotes.com/api
#
#   Requires:
#       * Internet
#       * curl
#       * w3m
#       * perl

url="http://iheartquotes.com/api/v1/random?$1"

curl $url 2> /dev/null | w3m -dump -T text/html
