#!/usr/bin/env zsh
#
#   Display commits that differ between two branches
#
#       git diff-branch [<branch1>] [<branch2>]
#
#   Two branches can be given, and a diff between them will be displayed
#
#   If one branch is given, the current branch is diffed against it
#
#   If no branches are given, the current branch is diffed against master


if [[ $# > 1 ]]; then
    #   Two branches can be given, and a diff between them will be displayed
    branch1=$1
    branch2=$2
elif [[ $# > 0 ]]; then
    #   If one branch is given, the current branch is diffed against it
    branch1=$(git symbolic-ref --short HEAD)
    branch2=$1
else
    #   If no branches are given, the current branch is diffed against master
    branch1=$(git symbolic-ref --short HEAD)
    branch2="master"
fi

autoload colors && colors
printf "\n%-75s$fg_bold[green]|$reset_color%75s\n" "< $fg_bold[blue]$branch1$reset_color" "$fg_bold[blue]$branch2$reset_color >"
printf  "$fg_bold[green]--------------------------------------------------------------+--------------------------------------------------------------$reset_color\n"
diff -y =(git log --oneline $branch2..$branch1) =(git log --oneline $branch1..$branch2)
