#!/usr/bin/env ruby
#
#   Pseudo-crypt text by shifting each consonant and vowel one consonant or
#   vowel to the right (e.g., 'english' becomes 'iphmotj')
#
#   The idea is that the transform leaves the text sort of pronounceable.
#
#   Handles text as arguments or from STDIN.  Non-letters are ignored.
#
#   NOTE:  This is NOT any kind of secure crypto.  This is for fun.

class String

    def iphmotj

        encodings = [
            'bcdfghjklmnpqrstvwxz',
            'aeiouy',
            'BCDFGHJKLMNPQRSTVWXZ',
            'AEIOUY',
            '0123456789'
        ]

        encoded = self.split(//).collect do |char|
            encodings.collect do |list|
                index = list.index(char)
                list[( index + 1 ) % list.length] if index
            end
        end

        encoded.join("")

    end

end

# Get the text to be encoded, either passed in as an arg or read from STDIN
plain = (ARGV.length > 0 ? ARGV[0] : gets)

# Print the encoding
puts plain.iphmotj
