#!/usr/bin/env ruby
#
#   Pseudo-crypt text by shifting each consonant and vowel one consonant or
#   vowel to the right (e.g., 'english' becomes 'iphmotj')
#
#   The idea is that the transform leaves the text sort of pronounceable.
#
#   Handles text as arguments or from STDIN.  Non-letters are ignored.
#
#   NOTE:  This is NOT any kind of secure crypto.  This is for fun.

plain = (ARGV.length > 0 ? ARGV[0] : gets)

class String

    def iphmotj

        encodings = [
            'bcdfghjklmnpqrstvwxz',
            'aeiouy',
            'BCDFGHJKLMNPQRSTVWXZ',
            'AEIOUY',
            '0123456789'
        ]

        encoded = ""

        self.split(//).each do |char|
            encodings.each do |list|
                index = list.index(char)
                encoded += list[( index + 1 ) % list.length] if index
            end
        end

        encoded

    end

end

puts plain.iphmotj
