#!/usr/bin/env zsh
#
#   Quickly and easily record notes
#
#   USAGE: jot <whatever>
#
#   Records <whatever> in a file, named after today, with each entry
#   time-stamped.  Can be a good way to keep track of what you spent your time
#   on, your path through a problem, etc.
#
#   Credit for the idea goes to jamesbritt at HN:
#       https://news.ycombinator.com/item?id=6897425
#
#   Blame for the implementation is mine.  :)

# Different file each day
jotfile="$HOME/jot/$(date +%F).txt"

# Timestamp each jot
echo "$(date +%r): $*" >> $jotfile
