#!/usr/bin/env zsh
#
# Quickly and easily record notes
#
# USAGE: jot <whatever>
#
# Records <whatever> in a file, along with timestamps and working dir.  Can be
# a good way to keep track of what you spent your time on, your path through a
# problem, etc.
#
# Credit for the idea goes to jamesbritt at HN:
# https://news.ycombinator.com/item?id=6897425
#
# Blame for the implementation is mine.  :)
#
# Jon Carter borkabrak@gmail.com
#
# TODO: 
#   Options to:
#   * Take a 'topic' and categorize by that.
#   * When listing last few entries, select most recent file to use (as it
#     might not be today's)

jotdir="$HOME/jot";

# If no params, show last few entries
if [[ $ARGC == 0 ]] then
    pushd -q ~/jot; grep -H "." *(n) | tail -5; popd -q
    exit;
fi

# If directory does not exist, create it.
if [[ ! -d $jotdir ]] then
    mkdir $jotdir
fi

# Different file each day
jotfile="$HOME/jot/$(date +%F).txt"

entry="$(date +%r):$(pwd): $*" 

# Also add timestamp and working dir.
echo $entry >> $jotfile
