#!/usr/bin/env zsh
lines_to_display=5
#
# Quickly and easily record notes
#
# USAGE: jot [<string>]
#
# Records <string> in a file, along with timestamps and working dir.  Can be
# a good way to keep track of what you spent your time on, your path through a
# problem, etc.
#
# Credit for the idea goes to jamesbritt at HN:
# https://news.ycombinator.com/item?id=6897425
#
# Blame for the implementation is mine.  :)
#
# Jon Carter borkabrak@gmail.com
#
# TODO:
#   Options to:
#   * Take a 'topic' and categorize by that.
#
#   * Pass an argument to search by

jotdir="$HOME/jot";
if [[ ! -d $jotdir ]]; then
    echo "$jotdir does not exist"
    exit;
fi

# If no params, show last few entries
if [[ $ARGC == 0 ]] then

    # Print something reasonable when there are not yet any jots
    if [[ $(ls $jotdir) == "" ]]; then
        echo "No jots";
        exit;
    fi

    pushd -q $jotdir
    grep -H . *(n) | tail -$lines_to_display
    popd -q
    exit;
fi

# If directory does not exist, create it.
if [[ ! -d $jotdir ]] then
    mkdir $jotdir
fi

# Different file each day
jotfile="$HOME/jot/$(date +%F).txt"

# Respond to subcommands
if [[ $1 == "grep" ]]; then
    # The remaining arguments are for grep, though we can assume a recursive
    # directory search on where the jots are stored.
    shift
    grep --color -r $@ $jotdir
    exit
fi

entry="$(date +%r):$(pwd): $*" 

# Also add timestamp and working dir.
echo $entry >> $jotfile
