#!/usr/bin/env zsh
#

# ZSNES hangs the whole damn desktop.  Restart the whole mess
#
echo "Killing zsnes.."
kill -9 $(pgrep zsnes | grep -v grep | head -1)
echo "Done"

echo "Need sudo password to restart gdm.."
sudo service gdm restart
echo "Restarting gdm.."
