#!/usr/bin/env zsh
#
#   Start writing a new script.  If it already exists, open it without changing
#   its contents.

script_directory="/home/jon/bin/"

function usage() {
cat <<-END
    $0: Start writing a new script.  If it already exists, open it without
    changing its contents.

    Usage: $0 <language> <name>

END
}

# Validate params
if [[ $# -lt 2 ]]; then
    usage
    exit
fi
 
language=$1
shift
name="$script_directory$1"
shift

# If the script does not currently exist, create it (as a script)
if [ ! -f $name ]; then
    touch $name
    chmod +x $name
    echo "#!/usr/bin/env $language\n# " > $name
fi

$EDITOR $name

