#!/usr/bin/env zsh
#
# Use sox to play various sounds

function usage(){
cat <<END

Use sox to play various sounds (most of which are pulled from the man page)

  USAGE: sfx <sound>

  Sounds: chime, guitar, organ, tone, warble

END
}

if [[ $1 == 'chime' ]]; then
  play -q -n synth -j 3 sin %3 sin %-2 sin %-5 sin %-9 \
    sin %-14 sin %-21 fade h .01 2 1.5 delay \
    1.3 1 .76 .54 .27 remix - fade h 0 2.7 2.5 norm -1

elif [[ $1 == 'guitar' ]]; then
  play -q -n synth pl G2 pl B2 pl D3 pl G3 pl D4 pl G4 \
    delay 0 .05 .1 .15 .2 .25 remix - fade 0 4 .1 norm -1

elif [[ $1 == 'organ' ]]; then
 play -q -n -c1 synth sin %-12 sin %-9 sin %-5 sin %-2 fade h 0.3 2 0.5

elif [[ $1 == 'tone' ]]; then
 play -q "| sox -n -p synth 2"

elif [[ $1 == 'warble' ]]; then
  play -n synth 2.5 sin 667 gain 1 \
    bend .35,180,.25  .15,740,.53  0,-520,.3

else 
  usage;
  exit;
fi
