#!/usr/bin/env zsh
#
# Print a sorted table of file/dir disk usages in various units
#
# Dependencies:
#   * zsh
#   * perl
#   * du
#   * sort

if [[ $1 =~ '--help|-h' ]]; then
  echo "USAGE: $0 [target directory]     # optional: defaults to current directory"
  exit
fi

# Switch to target directory
if [[ $# -gt 0 ]]; then

    cd $1 || exit

fi

# Get sizes sorted by bytes
du -s *(D) |
sort -rn |

perl -ne '

  # Print a header line
  BEGIN { 
    printf "TOTAL(GB)         KB       MB     GB              Filename\n";
    print "-" x 58; print "\n";
    my $total = 0;
  }

  # Grab the size explicitly and allow the rest of the line to be the filename, spaces and all
  ($b, $f) = (/(\d+)\s+(.*)/);   

  # Calculate units and format output
  ($g, $m) = ($b / 1024 / 1024, $b / 1024);
  $total += $g;
  printf("[%7.2f] %10.0f  %7.0f  %5.1f  %20s\n", $total, $b, $m, $g, $f)
'
