#!/usr/bin/env zsh
#
# Get/Set volume, reporting final volume as a percentage of max
#
#   Outputs the final volume percentage and raises a desktop notification.
#
#   USAGE EXAMPLES:
#
#   # Show current volume
#   $ vol
#
#   # Set volume to 50%
#   $ vol 50%
#
#   # Increase volume by twelve percent
#   $ vol 12%+
#
#   # Decrease volume by nine decibles
#   $ vol 9dB-

# Set volume (if given a target)
if [[ -n $1 ]]; then
    amixer set Master $1 | grep -o '[0-9]\+%' > /dev/null
fi

# Get volume
volume=$(amixer get Master | grep -o '[0-9]\+%' | grep -o '[0-9]*')

# Select an icon based on volume level
icon="audio-volume-high"
if [[ $volume -le 66 ]]; then
    icon="audio-volume-medium"
fi
if [[ $volume -le 33 ]]; then
    icon="audio-volume-low"
fi
if [[ $volume -le 0  ]]; then
    icon="audio-volume-muted"
fi

# Show volume..

# on the console
echo $volume

# As a notification bubble
#notify-send --expire-time 1000 -i $icon "$volume%"
