#!/usr/bin/env zsh
#
#   Just start writing.
#
#   Opens a (optionally named) file in the editor without having to worry about
#   directories, filenames, etc.
#
#   TODO: If <file> exists in $PATH, or something, open it there?

# Reasonable default filename
filename=$(date -I).mkd

# A user-specified filename takes precedence
if [[ $# > 0 ]]; then
  filename=$1
fi

# Reasonable default location
cd ~/documents/write

# Silently create any directories necessary
mkdir -p $(dirname $filename)
# Open file
$EDITOR $filename
