#!/usr/bin/env zsh
#
file_extension="mkd"
# Start writing.
writedir=~/documents/write

if [[ ! -z $1 ]]; then
  filename=$1
else
  # If not specified, open today's file.   
  filename=$(date -I).$file_extension
fi

if [[ ! -d $writedir ]]; then
  echo "$writedir does not exist"
  exit;
fi

$EDITOR $writedir/$filename
