#!/usr/bin/env zsh
#
# Start writing.  Open today's file.   

if [[ ! -z $1 ]]; then
  filename=$1
else
  filename=$(date +%F).txt
fi

writedir=~/write
if [[ ! -d $writedir ]]; then
  echo "$writedir does not exist"
  exit;
fi

$EDITOR $writedir/$filename
