#!/usr/bin/env zsh
#
#   zscript - Wrap zsh code in some options and settings more appropriate for
#   running as scripts.
#
#   Specify this file in the shebang line instead of the zsh executable:
#
#       #!/usr/bin/env zscript

# Exit on the first nonzero return code
setopt errexit

# Make available some useful script utilities
source ~/bin/zsh-utils

# TODO:
#  * Make sure vim recognizes 'zscript' in the shebang line the way it does 'zsh'.
#
#       (maybe start with :help ftplugin, to see how vim uses the shebang line to get filetype?)
#
#     In the meantime, adding a appropriate modeline to the script seems to work.  Like this:
#       vim: ft=zsh
#
#  * How can I ensure that we don't use user-defined aliases, making sure the
#  only options sent to the commands used by the scripts are the ones sent by
#  the script itself?  Unalias everything?  Hm..

# Adjust the argument list to what it would be if we ran the script normally.
scriptfile=$1
shift

# Execute the script
source $scriptfile
