#!/usr/bin/env ruby
#
#   The most hated, trivial programming interview task of all!
#   Here's the scoop:
#
#       Print the integers 1 through 100, but:
#           If divisible by 3, print "Fizz"
#           If divisible by 5, print "Buzz"
#           If divisible by 3 and 5, print "FizzBuzz"

# Sure, we could do it the *clear* way, but..
def fizznum_clear(n)
    return "FizzBuzz"   if (n % 15 == 0)
    return "Fizz"       if (n % 3 == 0)
    return "Buzz"       if (n % 5 == 0)
    return n
end


# ..dammit, Jonathan..
(1..100).each do |n|
    puts [  
            [15,    "Fizzbuzz"], 
            [3,         "Fizz"], 
            [5,         "Buzz"], 
            [n,              n] 
    ].find { |x| n % x[0] == 0 }[1]
end
