#!/usr/bin/env ruby

# Output time of day as a single binary number representing the number of
# minutes since the day began at midnight (0..1440)
#
# Why?  I really don't know what to say to that..
#

t = Time.new

binary_time = t.hour * 60 + t.min
puts "#{binary_time.to_s 2}"
