#!/usr/bin/zsh
# Reminder of how to color text

echo <<END
Set color: \\e[${i}m
Reset color back to normal: \\e[0m
More colors: \\e[38;5;${i}m
More info: http://en.wikipedia.org/wiki/ANSI_escape_code
END
for i in $(seq 0 255); do echo "\e[38;5;${i}mThis is ANSI color code $i"; done
